### PR TITLE
🌱 switch to logicalcluster.v3

### PR DESCRIPTION
**Pull request by p0lyn0mial**
## Summary
This PR switches the code-generator repository to use logicalcluster.v3 and also bumps the major version number for this repository to v2 in the go.mod file. That means that users will have to import it as github.com/kcp-dev/code-generator/v2

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
do we want to create `v2` for this pkg?

**Comment by sttts** [comment]
> do we want to create v2 for this pkg?

Yes

**Comment by p0lyn0mial** [comment]
fyi: i'm going to revert https://github.com/kcp-dev/code-generator/pull/74/commits/9ebb7f6fdd310472202ae527744b9fbbdec5cf16 once we merge https://github.com/kcp-dev/client-go/pull/20

**Pull request merged**
